language: csharp
mono: none
dotnet: 2.1.502
script:
 - dotnet restore
 - dotnet build
 - dotnet publish
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "omid eidivandi"
  - git config --local user.email "eidivandi@live.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: f9f58c5c0c9d414ec1fb4085f5a715df088be9cb 
  file: "test11111111"
  skip_cleanup: true 
