language: csharp
mono: none
dotnet: 2.1.502
script:
 - dotnet restore
 - dotnet build
 - dotnet publish
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name ""
  - git config --local user.email ""
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:  
  file: "test11111111"
  skip_cleanup: true 
